@admin_jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiYWRtaW5AbG9jYWxob3N0Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY3NDU3NTQ0MCwiZXhwIjoxNjc1MTgwMjQwfQ.hJcXtwoTnUHUIdW9MbMzYWCBoNsGybq0VvZdeyAWESQ

@admin_email=admin@localhost
@admin_pass=admin
@user_jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiYW5pYUBsb2NhbGhvc3QiLCJyb2xlIjoidXNlciJ9LCJpYXQiOjE2NzQ1NzU0MTIsImV4cCI6MTY3NTE4MDIxMn0.nG51o0W8vveFMCLJ0BC82w7qZnP3R482-cmEs_gkJtg

@user_email=ania@LOCALHOST
@user_pass=ania

@book_id=63c415e8ec82ababbea1f69c
# best to delete books added by POST here
@book_id_to_del=63b2cbec5d30e7e157cb4dbc

@shelf_id=63c415eaec82ababbea1f6c6
@shelf_id_to_del=63b21af41024b3a4a146d200
@shelf_id_2=63c415e9ec82ababbea1f6c3


@book_details_id=63c415ecec82ababbea1f6f8
@book_details_id_to_delete=63b2fe66b83427779bcc8759

@token_jwt= {{user_jwt}}
###
######## Auth
###
# Create account
POST http://localhost:3000/auth/signup
Content-Type: application/json
Accept: application/json

{
    "email": "admin@localhost",
    "password": "admin",
    "role": "admin"
}

###
# Create account
POST http://localhost:3000/auth/signup
Content-Type: application/json
Accept: application/json

{
    "email": "ania3@localhost",
    "password": "ania"

}

###
# Create account
POST http://localhost:3000/auth/signup
Content-Type: application/json
Accept: application/json

{
    "email": "ania6@localhost",
    "password": "ania",
    "avatar_url": "https://www.wp.pl",
    "username": "Anna",
    "role": "xxxxx"

}

###
# Login ok
POST http://localhost:3000/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "{{admin_email}}",
    "password": "{{admin_pass}}"
}
###
# Login ok
POST http://localhost:3000/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "{{user_email}}",
    "password": "{{user_pass}}"
}


###
# Login bad
POST http://localhost:3000/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "w@w",
    "password": "wx"
}

###
# verify if token is ok - logged in
GET  http://localhost:3000/auth/verification
Authorization: Bearer {{token_jwt}}



###
GET http://localhost:3000/books
Authorization: Bearer {{token_jwt}}

###
GET http://localhost:3000/books?search=Amber
Authorization: Bearer {{token_jwt}}

###
# Get one book
# GET http://localhost:3000/books/{{book_id}}
GET http://localhost:3000/books/63c415e9ec82ababbea1f6b7
Authorization: Bearer {{token_jwt}}

###
# Delete book
@book_id_to_del=63c415e8ec82ababbea1f69c
DELETE http://localhost:3000/books/{{book_id_to_del}}
Authorization: Bearer {{admin_jwt}}

###
POST http://localhost:3000/books
Content-Type: application/json
Authorization: Bearer {{admin_jwt}}

{
    "title": "Dune xxx",
    "author": "Frank Herbertxxxx",
    "cover": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1555447414l/44767458.jpg",
    "description": "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the “spice” melange, a drug capable of extending life and enhancing consciousness. Coveted across the known universe, melange is a prize worth killing for..",
    "edition": "Deluxe Edition",
    "pages": 658,
    "publishing_date": "2019-10-1",
    "publisher": "Ace Books",
    "serie": "Dune",
    "part_of_series": 1
}

###

PATCH http://localhost:3000/books/63b1fe77c2be0e799efef3a9
Authorization: Bearer {{token_jwt}}
Content-Type: application/json

{
    "title": "Dune 1x",
    "author": "Frank Herbert 2"
}


####### Shelves
###
GET http://localhost:3000/shelves
Authorization: Bearer {{token_jwt}}

###
# Get one 
GET http://localhost:3000/shelves/{{shelf_id}}
Authorization: Bearer {{token_jwt}}

###

###
# Delete 
DELETE http://localhost:3000/shelves/{{shelf_id_to_del}}
Authorization: Bearer {{token_jwt}}


###
# Add new shelf
POST http://localhost:3000/shelves
Content-Type: application/json
Authorization: Bearer {{user_jwt}}

{
    "name": "Fantastyka",
    "type": "custom",
    "sort": 100
}

###
POST http://localhost:3000/shelves
Content-Type: application/json
Authorization: Bearer {{user_jwt}}

{
    "name": "Kryminał",
    "type": "custom",
    "sort": 100

}

###

PATCH http://localhost:3000/shelves/{{shelf_id}}
Content-Type: application/json
Authorization: Bearer {{token_jwt}}


{
    "user": "{{admin_email}}"

}

########## Bazy danych - usuwanie kolekcji (pozyteczne przy testach)

###
DELETE http://localhost:3000/dbs/ala
Authorization: Bearer {{token_jwt}}

###
DELETE http://localhost:3000/dbs/bookdetails
Authorization: Bearer {{admin_jwt}}

#########
# BookDetails
# all books from user
GET http://localhost:3000/book-details
Authorization: Bearer {{token_jwt}}

###
# BookDetails
# search book-details for book_id for user
GET http://localhost:3000/book-details?book_id=63c415e9ec82ababbea1f6b7
Authorization: Bearer {{token_jwt}}



###
GET http://localhost:3000/book-details/{{book_details_id}}
Authorization: Bearer {{token_jwt}}

    
###
#63c415eaec82ababbea1f6c6
## Get all books from shelf
GET http://localhost:3000/book-details/shelves/{{shelf_id}}
Authorization: Bearer {{token_jwt}}


###
DELETE http://localhost:3000/book-details/{{book_details_id_to_delete}}
Authorization: Bearer {{token_jwt}}


###
@book_id_2=63cb125f671bf652498bc00c
POST http://localhost:3000/book-details
Content-Type: application/json
Authorization: Bearer {{token_jwt}}

{
    "book_id": "{{book_id_2}}",
    "rating": 5,
    "shelves": ["{{shelf_id}}","{{shelf_id_2}}"]
}

###
# PATCH http://localhost:3000/book-details/{{book_details_id}}
PATCH http://localhost:3000/book-details/63c415ecec82ababbea1f6f5
Content-Type: application/json
Authorization: Bearer {{token_jwt}}

{
    "rating": -1,
    "shelves": ["{{shelf_id}}","{{shelf_id_2}}","{{shelf_id}}"]

}


##### Users
###
# Get all
GET  http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{admin_jwt}}

###
# find user by substring in email or username
GET  http://localhost:3000/users?search=ania6
Content-Type: application/json
Authorization: Bearer {{admin_jwt}}



###
# Get one
GET  http://localhost:3000/users/{{user_email}}
Content-Type: application/json
Authorization: Bearer {{token_jwt}}


###
# delete account
DELETE  http://localhost:3000/users/{{user_email}}
Authorization: Bearer {{token_jwt}}


###

PATCH http://localhost:3000/users/{{user_email}}
Authorization: Bearer {{token_jwt}}
Content-Type: application/json

{
    "role": "user",
    "username": "Anna2"
}


###
##### Comments
###
# Get all
GET  http://localhost:3000/comments
Content-Type: application/json
Authorization: Bearer {{token_jwt}}

###
# Create comment
# @token_jwt={{admin_jwt}}
POST  http://localhost:3000/comments
Content-Type: application/json
Authorization: Bearer {{token_jwt}}

{
    "book_id": "{{book_id}}",
    "content": "To jest komentarz"
}

###
# @comment_id=63cc19aa12b5be9e23d0730b
@comment_id=63cc185a3e06dc1be933fa6a
# Get one
GET  http://localhost:3000/comments/{{comment_id}}
Content-Type: application/json
Authorization: Bearer {{token_jwt}}

###
# Search comments
# search - substring in content
# user - email of user
# book_id - id of book
# all params are optional
# all params are connected with AND
GET  http://localhost:3000/comments?book_id={{book_id}}
Content-Type: application/json
Authorization: Bearer {{token_jwt}}

###
# Delete comment
DELETE  http://localhost:3000/comments/{{comment_id}}
Content-Type: application/json
Authorization: Bearer {{token_jwt}}

###
# Update comment
PATCH  http://localhost:3000/comments/{{comment_id}}
Content-Type: application/json
Authorization: Bearer {{token_jwt}}

{
    "content": "To jest nowy komentarz"
}

###
# stats for books
GET  http://localhost:3000/stats
Content-Type: application/json
Authorization: Bearer {{token_jwt}}

###
# stats for books
# sort_direction=asc|desc
# limit=5
# stat_type=global|user
GET  http://localhost:3000/stats?sort_direction=asc&limit=5&stat_type=global
Content-Type: application/json
Authorization: Bearer {{token_jwt}}

###
GET  http://localhost:3000/stats?sort_direction=asc&limit=5
Content-Type: application/json
Authorization: Bearer {{token_jwt}}